GET http://localhost:5000/api/health HTTP/1.1

###
GET http://localhost:5000/api/collectors HTTP/1.1

###
POST http://localhost:5000/api/collectors HTTP/1.1
Content-Type: application/json

{
    "name": "James Bond",
    "email": "james.bond@mi6.gov.uk",
    "cars": "Aston Martin",
    "slogan": "Tomorrow never dies",
    "trading": false
}